######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 11 22:51:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PICViewer.h PICViewer.hpp
FORMS += PICViewer.ui
SOURCES += PICViewer.cpp
